version: '3.8'

services:
  txt-outlier-backend:
    build: .
    container_name: outlier-backend-python-container
    image: outlier-backend-python-image
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
